language: python
python:
    - 2.7
    - 3.3
    - 3.4
install:
    - pip install -r requirements.txt -r requirements-dev.txt
script:
    - make lint
    - make test
    - make docs-html
notifications:
    irc: "chat.freenode.net#robottelo"
