language: python
python:
    - 2.7
install:
    - pip install -r requirements.txt -r requirements-dev.txt
script:
    - flake8 .
    - make test
    - make docs-html
notifications:
    irc: "chat.freenode.net#robottelo"
